name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update repo README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull latest posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOGPOST"
          max_post_count: 8
          commit_message: "Updated readme with the latest Hashnode Blog data"
          feed_list: "https://feedly.com/i/subscription/feed//author/ayobami/https://www.freecodecamp.org/news/rss, https://aythedataguy.hashnode.dev/rss.xml"
